[project]
name = "advent-of-sql"
version = "1.0.0"
description = "Solutions to https://adventofsql.com/"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pytest>=8.4.1",
    "ruff>=0.12.9",
]
