[project]
name = "project-euler"
version = "1.0.0"
description = "Project Euler solutions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pytest>=8.4.1",
    "pytest-xdist>=3.8.0",
    "ruff>=0.12.9",
]

[tool.pytest.ini_options]
pythonpath = "."
