[project]
name = "everybody-codes"
version = "1.0.0"
description = "Solutions to everybody.codes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ruff>=0.12.10",
    "requests>=2.31.0",
    "pycryptodome>=3.19.0",
    "z3>=0.2.0",
    "sortedcontainers>=2.4.0",
]
