[project]
name = "pi-coding-quest-solutions"
version = "0.1.0"
description = "Solutions to Pi Coding Quest https://ivanr3d.com/projects/pi/"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pytest>=8.4.1",
]
