[project]
name = "xint-solutions"
version = "1.0.0"
description = "Solutions to https://salza.dk/xint/"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "mypy>=1.17.1",
    "requests>=2.32.4",
    "ruff>=0.12.8",
    "types-requests>=2.32.4.20250809",
]
