# Databricks notebook source
# MAGIC %md https://adventofcode.com/2020/day/17

# COMMAND ----------

# MAGIC %md <article class="day-desc"><h2>--- Day 17: Conway Cubes ---</h2><p>As your flight slowly drifts through the sky, the Elves at the Mythical Information Bureau at the North Pole contact you. They'd like some help debugging a malfunctioning experimental energy source aboard one of their super-secret imaging satellites.</p>
# MAGIC <p>The experimental energy source is based on cutting-edge technology: a set of <span title="Rest in peace, Conway.">Conway</span> Cubes contained in a pocket dimension! When you hear it's having problems, you can't help but agree to take a look.</p>
# MAGIC <p>The pocket dimension contains an infinite 3-dimensional grid. At every integer 3-dimensional coordinate (<code>x,y,z</code>), there exists a single cube which is either <em>active</em> or <em>inactive</em>.</p>
# MAGIC <p>In the initial state of the pocket dimension, almost all cubes start <em>inactive</em>. The only exception to this is a small flat region of cubes (your puzzle input); the cubes in this region start in the specified <em>active</em> (<code>#</code>) or <em>inactive</em> (<code>.</code>) state.</p>
# MAGIC <p>The energy source then proceeds to boot up by executing six <em>cycles</em>.</p>
# MAGIC <p>Each cube only ever considers its <em>neighbors</em>: any of the 26 other cubes where any of their coordinates differ by at most <code>1</code>. For example, given the cube at <code>x=1,y=2,z=3</code>, its neighbors include the cube at <code>x=2,y=2,z=2</code>, the cube at <code>x=0,y=2,z=3</code>, and so on.</p>
# MAGIC <p>During a cycle, <em>all</em> cubes <em>simultaneously</em> change their state according to the following rules:</p>
# MAGIC <ul>
# MAGIC <li>If a cube is <em>active</em> and <em>exactly <code>2</code> or <code>3</code></em> of its neighbors are also active, the cube remains <em>active</em>. Otherwise, the cube becomes <em>inactive</em>.</li>
# MAGIC <li>If a cube is <em>inactive</em> but <em>exactly <code>3</code></em> of its neighbors are active, the cube becomes <em>active</em>. Otherwise, the cube remains <em>inactive</em>.</li>
# MAGIC </ul>
# MAGIC <p>The engineers responsible for this experimental energy source would like you to simulate the pocket dimension and determine what the configuration of cubes should be at the end of the six-cycle boot process.</p>
# MAGIC <p>For example, consider the following initial state:</p>
# MAGIC <pre><code>.#.
# MAGIC ..#
# MAGIC ###
# MAGIC </code></pre>
# MAGIC <p>Even though the pocket dimension is 3-dimensional, this initial state represents a small 2-dimensional slice of it. (In particular, this initial state defines a 3x3x1 region of the 3-dimensional space.)</p>
# MAGIC <p>Simulating a few cycles from this initial state produces the following configurations, where the result of each cycle is shown layer-by-layer at each given <code>z</code> coordinate (and the frame of view follows the active cells in each cycle):</p>
# MAGIC <pre><code>Before any cycles:
# MAGIC 
# MAGIC z=0
# MAGIC .#.
# MAGIC ..#
# MAGIC ###
# MAGIC 
# MAGIC 
# MAGIC After 1 cycle:
# MAGIC 
# MAGIC z=-1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=0
# MAGIC #.#
# MAGIC .##
# MAGIC .#.
# MAGIC 
# MAGIC z=1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC 
# MAGIC After 2 cycles:
# MAGIC 
# MAGIC z=-2
# MAGIC .....
# MAGIC .....
# MAGIC ..#..
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-1
# MAGIC ..#..
# MAGIC .#..#
# MAGIC ....#
# MAGIC .#...
# MAGIC .....
# MAGIC 
# MAGIC z=0
# MAGIC ##...
# MAGIC ##...
# MAGIC #....
# MAGIC ....#
# MAGIC .###.
# MAGIC 
# MAGIC z=1
# MAGIC ..#..
# MAGIC .#..#
# MAGIC ....#
# MAGIC .#...
# MAGIC .....
# MAGIC 
# MAGIC z=2
# MAGIC .....
# MAGIC .....
# MAGIC ..#..
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC 
# MAGIC After 3 cycles:
# MAGIC 
# MAGIC z=-2
# MAGIC .......
# MAGIC .......
# MAGIC ..##...
# MAGIC ..###..
# MAGIC .......
# MAGIC .......
# MAGIC .......
# MAGIC 
# MAGIC z=-1
# MAGIC ..#....
# MAGIC ...#...
# MAGIC #......
# MAGIC .....##
# MAGIC .#...#.
# MAGIC ..#.#..
# MAGIC ...#...
# MAGIC 
# MAGIC z=0
# MAGIC ...#...
# MAGIC .......
# MAGIC #......
# MAGIC .......
# MAGIC .....##
# MAGIC .##.#..
# MAGIC ...#...
# MAGIC 
# MAGIC z=1
# MAGIC ..#....
# MAGIC ...#...
# MAGIC #......
# MAGIC .....##
# MAGIC .#...#.
# MAGIC ..#.#..
# MAGIC ...#...
# MAGIC 
# MAGIC z=2
# MAGIC .......
# MAGIC .......
# MAGIC ..##...
# MAGIC ..###..
# MAGIC .......
# MAGIC .......
# MAGIC .......
# MAGIC </code></pre>
# MAGIC <p>After the full six-cycle boot process completes, <em><code>112</code></em> cubes are left in the <em>active</em> state.</p>
# MAGIC <p>Starting with your given initial configuration, simulate six cycles. <em>How many cubes are left in the active state after the sixth cycle?</em></p>
# MAGIC </article>

# COMMAND ----------

inp = '''.#.####.
.#...##.
..###.##
#..#.#.#
#..#....
#.####..
##.##..#
#.#.#..#'''

# COMMAND ----------

import itertools

def simulate(actives):
  neighbors = {}
  for p in actives:
    for delta in itertools.product(*(((-1, 0, 1),) * len(p))):
      p2 = tuple(x + dx for x, dx in zip(p, delta))
      if p2 == p:
        continue

      neighbors[p2] = neighbors.get(p2, 0) + 1
  
  new_actives = set()
  for p, cnt in neighbors.items():
    if p in actives and cnt in [2, 3]:
      new_actives.add(p)
    elif p not in actives and cnt == 3:
      new_actives.add(p)

  actives.clear()
  actives.update(new_actives)


actives_start = {(x, y, 0) for y, line in enumerate(inp.splitlines()) for x, c in enumerate(line) if c == '#'}

actives = actives_start.copy()
for _ in range(6):
  simulate(actives)

answer = len(actives)
print(answer)

# COMMAND ----------

# MAGIC %md <article class="day-desc"><h2 id="part2">--- Part Two ---</h2><p>For some reason, your simulated results don't match what the experimental energy source engineers expected. Apparently, the pocket dimension actually has <em>four spatial dimensions</em>, not three.</p>
# MAGIC <p>The pocket dimension contains an infinite 4-dimensional grid. At every integer 4-dimensional coordinate (<code>x,y,z,w</code>), there exists a single cube (really, a <em>hypercube</em>) which is still either <em>active</em> or <em>inactive</em>.</p>
# MAGIC <p>Each cube only ever considers its <em>neighbors</em>: any of the 80 other cubes where any of their coordinates differ by at most <code>1</code>. For example, given the cube at <code>x=1,y=2,z=3,w=4</code>, its neighbors include the cube at <code>x=2,y=2,z=3,w=3</code>, the cube at <code>x=0,y=2,z=3,w=4</code>, and so on.</p>
# MAGIC <p>The initial state of the pocket dimension still consists of a small flat region of cubes. Furthermore, the same rules for cycle updating still apply: during each cycle, consider the <em>number of active neighbors</em> of each cube.</p>
# MAGIC <p>For example, consider the same initial state as in the example above. Even though the pocket dimension is 4-dimensional, this initial state represents a small 2-dimensional slice of it. (In particular, this initial state defines a 3x3x1x1 region of the 4-dimensional space.)</p>
# MAGIC <p>Simulating a few cycles from this initial state produces the following configurations, where the result of each cycle is shown layer-by-layer at each given <code>z</code> and <code>w</code> coordinate:</p>
# MAGIC <pre><code>Before any cycles:
# MAGIC 
# MAGIC z=0, w=0
# MAGIC .#.
# MAGIC ..#
# MAGIC ###
# MAGIC 
# MAGIC 
# MAGIC After 1 cycle:
# MAGIC 
# MAGIC z=-1, w=-1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=0, w=-1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=1, w=-1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=-1, w=0
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=0, w=0
# MAGIC #.#
# MAGIC .##
# MAGIC .#.
# MAGIC 
# MAGIC z=1, w=0
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=-1, w=1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=0, w=1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC z=1, w=1
# MAGIC #..
# MAGIC ..#
# MAGIC .#.
# MAGIC 
# MAGIC 
# MAGIC After 2 cycles:
# MAGIC 
# MAGIC z=-2, w=-2
# MAGIC .....
# MAGIC .....
# MAGIC ..#..
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-1, w=-2
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=0, w=-2
# MAGIC ###..
# MAGIC ##.##
# MAGIC #...#
# MAGIC .#..#
# MAGIC .###.
# MAGIC 
# MAGIC z=1, w=-2
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=2, w=-2
# MAGIC .....
# MAGIC .....
# MAGIC ..#..
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-2, w=-1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-1, w=-1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=0, w=-1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=1, w=-1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=2, w=-1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-2, w=0
# MAGIC ###..
# MAGIC ##.##
# MAGIC #...#
# MAGIC .#..#
# MAGIC .###.
# MAGIC 
# MAGIC z=-1, w=0
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=0, w=0
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=1, w=0
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=2, w=0
# MAGIC ###..
# MAGIC ##.##
# MAGIC #...#
# MAGIC .#..#
# MAGIC .###.
# MAGIC 
# MAGIC z=-2, w=1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-1, w=1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=0, w=1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=1, w=1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=2, w=1
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-2, w=2
# MAGIC .....
# MAGIC .....
# MAGIC ..#..
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=-1, w=2
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=0, w=2
# MAGIC ###..
# MAGIC ##.##
# MAGIC #...#
# MAGIC .#..#
# MAGIC .###.
# MAGIC 
# MAGIC z=1, w=2
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC .....
# MAGIC 
# MAGIC z=2, w=2
# MAGIC .....
# MAGIC .....
# MAGIC ..#..
# MAGIC .....
# MAGIC .....
# MAGIC </code></pre>
# MAGIC <p>After the full six-cycle boot process completes, <em><code>848</code></em> cubes are left in the <em>active</em> state.</p>
# MAGIC <p>Starting with your given initial configuration, simulate six cycles in a 4-dimensional space. <em>How many cubes are left in the active state after the sixth cycle?</em></p>
# MAGIC </article>

# COMMAND ----------

actives = {(x, y, z, 0) for x, y, z in actives_start}
for _ in range(6):
  simulate(actives)

answer = len(actives)
print(answer)
