[project]
name = "python"
version = "1.0.0"
description = "Solutions to Advent of Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "advent-of-code-data>=2.1.0",
    "numpy>=2.3.5",
    "scikit-learn>=1.7.2",
    "shapely>=2.1.2",
    "sortedcontainers>=2.4.0",
    "z3-solver>=4.15.4.0",
]

[[tool.ty.overrides]]
include = ["aocd.*"]
rules.invalid-argument-type = "ignore"
