# Databricks notebook source


# COMMAND ----------

# MAGIC %md https://adventofcode.com/2015/day/25

# COMMAND ----------

# MAGIC %md <article class="day-desc"><h2>--- Day 25: Let It Snow ---</h2><p>Merry Christmas!  Santa is booting up his weather machine; looks like you might get a <a href="1">white Christmas</a> after all.</p>
# MAGIC <p>The weather machine beeps!  On the console of the machine is a copy protection message asking you to <a href="https://en.wikipedia.org/wiki/Copy_protection#Early_video_games">enter a code from the instruction manual</a>.  Apparently, it refuses to run unless you give it that code.  No problem; you'll just look up the code in the--</p>
# MAGIC <p>"Ho ho ho", Santa ponders aloud.  "I can't seem to find the manual."</p>
# MAGIC <p>You look up the support number for the manufacturer and give them a call.  Good thing, too - that 49th star wasn't going to earn itself.</p>
# MAGIC <p>"Oh, that machine is quite old!", they tell you.  "That model went out of support six minutes ago, and we just finished shredding all of the manuals.  I bet we can find you the code generation algorithm, though."</p>
# MAGIC <p>After putting you on hold for twenty minutes (your call is <em>very</em> important to them, it reminded you repeatedly), they finally find an engineer that remembers how the code system works.</p>
# MAGIC <p>The codes are printed on an <span title="The paper is very thin so it can be folded up neatly into the manual.">infinite sheet of paper</span>, starting in the top-left corner.  The codes are filled in by diagonals: starting with the first row with an empty first box, the codes are filled in diagonally up and to the right.  This process repeats until the <a href="https://en.wikipedia.org/wiki/Cantor's_diagonal_argument">infinite paper is covered</a>.  So, the first few codes are filled in in this order:</p>
# MAGIC <pre><code>   | 1   2   3   4   5   6  
# MAGIC ---+---+---+---+---+---+---+
# MAGIC  1 |  1   3   6  10  15  21
# MAGIC  2 |  2   5   9  14  20
# MAGIC  3 |  4   8  13  19
# MAGIC  4 |  7  12  18
# MAGIC  5 | 11  17
# MAGIC  6 | 16
# MAGIC </code></pre>
# MAGIC <p>For example, the 12th code would be written to row <code>4</code>, column <code>2</code>; the 15th code would be written to row <code>1</code>, column <code>5</code>.</p>
# MAGIC <p>The voice on the other end of the phone continues with how the codes are actually generated.  The first code is <code>20151125</code>.  After that, each code is generated by taking the previous one, multiplying it by <code>252533</code>, and then keeping the remainder from dividing that value by <code>33554393</code>.</p>
# MAGIC <p>So, to find the second code (which ends up in row <code>2</code>, column <code>1</code>), start with the previous value, <code>20151125</code>.  Multiply it by <code>252533</code> to get <code>5088824049625</code>.  Then, divide that by <code>33554393</code>, which leaves a remainder of <code>31916031</code>.  That remainder is the second code.</p>
# MAGIC <p>"Oh!", says the voice.  "It looks like we missed a scrap from one of the manuals.  Let me read it to you."  You write down his numbers:</p>
# MAGIC <pre><code>   |    1         2         3         4         5         6
# MAGIC ---+---------+---------+---------+---------+---------+---------+
# MAGIC  1 | 20151125  18749137  17289845  30943339  10071777  33511524
# MAGIC  2 | 31916031  21629792  16929656   7726640  15514188   4041754
# MAGIC  3 | 16080970   8057251   1601130   7981243  11661866  16474243
# MAGIC  4 | 24592653  32451966  21345942   9380097  10600672  31527494
# MAGIC  5 |    77061  17552253  28094349   6899651   9250759  31663883
# MAGIC  6 | 33071741   6796745  25397450  24659492   1534922  27995004
# MAGIC </code></pre>
# MAGIC <p>"Now remember", the voice continues, "that's not even all of the first few numbers; for example, you're missing the one at 7,1 that would come before 6,2.  But, it should be enough to let your-- oh, it's time for lunch!  Bye!"  The call disconnects.</p>
# MAGIC <p>Santa looks nervous.  Your puzzle input contains the message on the machine's console.  <em>What code do you give the machine?</em></p>
# MAGIC </article>

# COMMAND ----------

library(tidyverse)

# COMMAND ----------

input <- "To continue, please consult the code grid in the manual.  Enter the code at row 2947, column 3029.
"

# COMMAND ----------

target_row <- str_extract(input, "(?<=row )\\d+") %>% parse_integer()
target_column <- str_extract(input, "(?<=column )\\d+") %>% parse_integer()

lst(target_row, target_column)

# COMMAND ----------

code <- 20151125
row <- 1
column <- 1
lowest_row <- 1

while (!(row == target_row && column == target_column)) {
  code <- (code * 252533) %% 33554393
  if (row == 1) {
    lowest_row <- lowest_row + 1
    row <- lowest_row
    column = 1
  } else {
    row <- row - 1
    column <- column + 1
  }
}

answer <- code
answer

# COMMAND ----------

# MAGIC %md <article class="day-desc"><h2 id="part2">--- Part Two ---</h2><p>The machine springs to life, then falls silent again.  It beeps.  "Insufficient fuel", the console reads.  "<em class="star">Fifty stars</em> are required before proceeding.  <em class="star">One star</em> is available."</p>
# MAGIC <p>..."one star is available"?  You check the fuel tank; sure enough, a lone star sits at the bottom, awaiting its friends.  Looks like you need to provide 49 yourself.</p>
# MAGIC </article>

# COMMAND ----------

# No puzzle here - just need all the stars
